name: Build EverMedia Plugin

on:
  push:
    branches: [ "main", "d*" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: read

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - uses: actions/checkout@v4

    - name: Setup.NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: EverMedia
        path: ./bin/Release/net8.0/EverMedia.dll
        if-no-files-found: error
        retention-days: 7

    - name: Create Release for Tags
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: ./bin/Release/net8.0/EverMedia.dll
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
